version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - REGION=$(aws configure get region)
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/my-ecr:$CODEBUILD_BUILD_NUMBER"
      - docker build -t "$IMAGE_URI" .
      - docker push "$IMAGE_URI"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
